# (More on) Numpy

**Camilo A. Garcia Trillos**

---

## In this notebook 

We learn more about the Numpy package: we look at arrays and matrices, and some of the associated modules.


We start by importing the modules we will use in this notebook: only numpy.

In [1]:
import numpy as np

<a id="arrays"></a>

## More on arrays

Let us look deeper at the numpy library. The numpy library contains useful tools to work with vectors and matrices, solve linear operations and generate random entries.


We have a look at data types and their implications, basic operations, some canonical matrices, matrix inversion and solution of linear systems.





In [2]:
a = np.array([1,3,6,1])

In [3]:
a

array([1, 3, 6, 1])

Two important methods for arrays are *size* and *shape*. The former give sus the total number of elements in an array. The latter tells us how these elements are organised, whcih is particularly useful to define matrices or higher order tensors.

In [4]:
a.size # The number of total elements in the array

4

In [5]:
a.shape

(4,)

This means that at this time, all elements are organised in a unique row. We can render this vector into a 'column vector' or into a 2x2 matrix *with the same entries* simply assigning the shape we want or by using the *reshape* method.

In [6]:
print('original')
print(a)
a.shape=(1,4)
print('column vector (inplace)')
print(a)
b = a.reshape(2,2)
print('matrix')
print(b)



original
[1 3 6 1]
column vector (inplace)
[[1 3 6 1]]
matrix
[[1 3]
 [6 1]]


When assigning the *shape* property, the array itself changes (this is called 'inplace'):

In [7]:
a

array([[1, 3, 6, 1]])

In [8]:
print(a[0,1]) # This is OK
print(a[0]) # this is OK
a[1] #This is an error

3
[1 3 6 1]


IndexError: index 1 is out of bounds for axis 0 with size 1

The above error occurs because there is only one entry on the first dimension of the array.

Arrays, unlike lists, cannot in general combine different types of entries. The vector we created above was an integer vector (note the lack of dots at the end of all prints!). Hence, if we try to assign a float, we will get a roundup version of it

In [9]:
a[0,1] = 9.2

In [10]:
a

array([[1, 9, 6, 1]])

As mentioned above, 9.2 becomes 9. Let su try now by creating a vector of floats from the start:

In [11]:
b = np.array([1.0,3,6])

In [12]:
b

array([1., 3., 6.])

In [13]:
b[1] = 9.2

In [14]:
b

array([1. , 9.2, 6. ])

Note the difference!  The array b was initialized to have floats, thanks to writing 1.0 instead of 1.  Thus, in contrast to a, it contains 9.2 (instead of 9, as the array a does)

As *lists*, arrays are assigned by reference. What follows should not surprise you if you followed the first notebook.


In [15]:
c = b
c
c[0] = 7.1
print('c:',c)
print('b:', b)

c: [7.1 9.2 6. ]
b: [7.1 9.2 6. ]


If an independent copy of a given array is needed, we can use the method *copy*

In [16]:
c=b.copy()
c
c[1]=1
print(c)
print(b)

[7.1 1.  6. ]
[7.1 9.2 6. ]


In the previous notebook, we looked at the method *arange*. Here are ways to use it:

In [17]:
d = np.arange(3, 42, 7)
d

array([ 3, 10, 17, 24, 31, 38])

In [18]:
d = np.arange(38, 2, -7)
d

array([38, 31, 24, 17, 10,  3])

In [19]:
d = np.arange(10)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

<a id="broadcasting"></a>
## Broadcasting

We mentioned in the previous notebook that there was an exception to the rule of operating with the exact same dimensions. This exception is called broadcasting. Let us first present an example: try to figure out what is happening

**Example 1**

In [20]:
d.shape = (5,2)
d

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [21]:
e = np.array([1,3])

In [22]:
print(d * e)
print(d.shape, e.shape)

[[ 0  3]
 [ 2  9]
 [ 4 15]
 [ 6 21]
 [ 8 27]]
(5, 2) (2,)


**Example 2**

In [23]:
e.shape = (1,2)
print(d * e)
print(d.shape, e.shape)

[[ 0  3]
 [ 2  9]
 [ 4 15]
 [ 6 21]
 [ 8 27]]
(5, 2) (1, 2)


**Example 3**

In [24]:
f = np.array([1,1,1,2,2]).reshape(-1,1)
print('f: ',f, 'and the shape of f:', f.shape)

f:  [[1]
 [1]
 [1]
 [2]
 [2]] and the shape of f: (5, 1)


In [25]:
print(f*d)
print(f.shape, d.shape)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [12 14]
 [16 18]]
(5, 1) (5, 2)


**Example 4**

However, recall that the following gives an error:

In [26]:
g = np.array([1,2,3])
print(d.shape,g.shape)
print(g*d) # This gives an error

(5, 2) (3,)


ValueError: operands could not be broadcast together with shapes (3,) (5,2) 

If you have not figure it out, the explanation is as follows: suppose we are operating the arrays a and b. Suppose that the shape of a is $(m_1,m_2)$, while the shapes of b are $(n_1,n_2)$:
- If $n_i \neq m_i$  **and** both are different from one or empty for some $i=1, 2$, then the operation cannot be done.
- If $n_i \neq m_i$  **and** one of the two is equal to one or empty for some $i=1, 2$, then the operation is done by completing the missing dimensions via copying the remaining components.

Look again to the example to make sure you understand this process. In particular, see how the empty spaces can be accomodated to the above template.

**Note:** arrays can be *tensors*, i.e. have more than 2 dimensions. Broadcasting is generalised as you would expect.


**Example 5**

Observe the following example

In [27]:
d[0,0] = 1

In [28]:
d

array([[1, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [29]:
1/d

array([[1.        , 1.        ],
       [0.5       , 0.33333333],
       [0.25      , 0.2       ],
       [0.16666667, 0.14285714],
       [0.125     , 0.11111111]])

The above works, because 1 is taken as an array of empty size, so it can be broadcasted by repeating itself to operate on each entry.

Note though that the following is an error:

In [30]:
d ** (-1) # This raises an error

ValueError: Integers to negative integer powers are not allowed.

What's wrong?  We initialized d with integers, and there is no well defined change of type for this operation.

In [31]:
d.dtype # Observe the type of this array

dtype('int64')

In [32]:
d = d.astype(float) # Set it to float

In [33]:
d.dtype # Observe again the type

dtype('float64')

In [34]:
d ** (-1) # The correct answer appears.

array([[1.        , 1.        ],
       [0.5       , 0.33333333],
       [0.25      , 0.2       ],
       [0.16666667, 0.14285714],
       [0.125     , 0.11111111]])

In [35]:
(d ** (-1)) == (1/d)

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

<a id="canonical"></a>
## Some canonical matrices/vectors


Let us introduce some canonical matrices and vectors.

In [36]:
# Zeros and ones matrix/vector

print (np.zeros(10))
a = np.ones((2,5))
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


By default these are float. If an integer is desired, this  has to be stated explicitly.

In [37]:
b=np.zeros(10, dtype=int)
print (b)

[0 0 0 0 0 0 0 0 0 0]


Some other useful functions are zeros_like and ones_like: they create zeros and ones of the lentgh and type of the parameter

In [38]:
print(np.zeros_like(a))
print(np.ones_like(b))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1 1 1 1 1 1 1 1 1 1]


We have also an identity matrix and the function diag. Let us look at what they do:

In [39]:
c=np.eye(5)

In [40]:
c[2][2]=10
print(c)
print('=====')
print(np.diag(c))

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]
=====
[ 1.  1. 10.  1.  1.]


Diag can also be used to build a diagonal matrix, as shown below.

In [41]:
np.diag(np.arange(8))

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 0, 7]])

<a id="inverting"></a>
## Inverting a matrix

Recall how to generate a random Gaussian matrix: here we generate a matrix of size 3x3, where each entry is i.i.d. with distribution $\mathcal N(0,1)$

In [42]:
rng = np.random.default_rng()
g = rng.standard_normal(0,1,(3,3))
g

TypeError: Cannot interpret '1' as a data type

We can check that the matrix is invertible, by looking at the rank of the matrix

In [43]:
np.linalg.matrix_rank(g)

1

If the rank is 3 then we can invert the matrix g.  We already showed that *g ** (-1)* does not give the matrix inverse. Instead it computes the reciprocals of each component:

In [44]:
g ** (-1)

ValueError: Integers to negative integer powers are not allowed.

Instead the package numpy has a specific command to obtain the matrix inverse:

In [45]:
g_inv = np.linalg.inv(g)

LinAlgError: 1-dimensional array given. Array must be at least two-dimensional

In [46]:
g_inv

NameError: name 'g_inv' is not defined

Let's check:

In [47]:
g@g_inv

NameError: name 'g_inv' is not defined

Apart from rounding errors this is basically the identity matrix.

We need to be careful though:
- Inverting matrices is expensive
- Inversion is done numerically, and this algorithm is not *stable* when applied to certain matrices. 

Let us illustrate this point with an example. We are going to use another canonical matrix, the [Hilbert matrix](https://en.wikipedia.org/wiki/Hilbert_matrix). This matrix is famous for being ill conditioned (that is, there is a huge gap between its eigenvalues), which makes it a bad example for inversion algorithms.

In [48]:
from scipy.linalg import hilbert

dim = 13
ill_conditioned = hilbert(dim)
#ill_conditioned

In [49]:
np.linalg.cond(ill_conditioned)

4.4936679531246986e+18

In [50]:
ill_inverse = np.linalg.inv(ill_conditioned)
np.diag(ill_conditioned @ ill_inverse )   # If inverse is perfect, all entries here would be one (can you see why?)

array([ 1.00000001,  0.99999679,  1.00005931,  1.01171875,  0.99373929,
        1.31938418,  1.24354124,  1.42554633, -1.31935816,  3.06404964,
       -1.21930164,  1.16861758,  0.94777567])

In [51]:
b = np.ones(dim)
ill_conditioned @ (ill_inverse @ b) # If inverse is perfect, all entries here would be one (can you see why?)

array([-21.89711892, -21.65263147, -19.18224112, -17.1135844 ,
       -15.4517454 , -14.09137024, -12.95361918, -11.98483408,
       -11.14789288, -10.41627753,  -9.77044733,  -9.19561241,
        -8.68032324])

Note that the above tests show that we are not really getting a good approximation of the inverse.

There are several ways to account for this problem. One can add a small amount to the diagonal

In [52]:
ill_min = np.min(ill_conditioned)
ill_max = np.max(ill_conditioned)
print(ill_min,ill_max)

0.04 1.0


In [53]:
better_cond = ill_conditioned + np.diag (ill_min*0.05*np.ones(dim) )
better_inv = np.linalg.inv(better_cond)

In [54]:
ill_conditioned @ (better_inv @ b) # If inverse is perfect, all entries here would be one (can you see why?)

array([1.00160478, 0.99015151, 0.99379173, 1.00807935, 1.01921242,
       1.02373631, 1.02185175, 1.01473545, 1.00365078, 0.98968786,
       0.97371675, 0.95640769, 0.93826756])

Note that this solution is much closer to the one vector, and so the inverse is close to what we would like. 

But this solution has a *bias*, that is, we have a systematic error. A more expensive alternative is to add an error that is neglected in probability: we add  a small random amount to the matrix, and then average out a couple of solutions

In [55]:
noise_factor = np.diag(rng.random(dim) *0.02)

In [56]:
np.min(noise_factor), np.mean(noise_factor), np.max(noise_factor)

(0.0, 0.0007575742268037068, 0.017829949175215954)

In [57]:
better_cond2 = ill_conditioned + noise_factor
better_inv2 = np.linalg.inv(better_cond2)

In [58]:
ill_conditioned @ (better_inv2 @ b)

array([0.99768798, 0.99174766, 1.02935073, 1.04909548, 1.05155075,
       1.04209642, 1.02509003, 1.00352849, 0.97939302, 0.95397877,
       0.92812833, 0.90238645, 0.8771009 ])

This works specially well when the matrix is a calculated covariance matrix: in this case one can randomly perturb the data before calculating the covariance.

<a id="lin_sys"></a>

## Solving linear systems

Sometimes we are not interested in finding the inverse matrix but rather in solving a liner system like

$$A {\bf x} ={\bf b}$$

Doing this directly is usually more efficient.

There is a whole theory on how to solve linear equations(this is at the core of numerical analysis), but we will simply use the predifined functions.

In [59]:
x = np.linalg.solve(ill_conditioned, b)
x

array([-8.42636114e+01,  1.31058324e+04, -5.01040081e+05,  8.27215678e+06,
       -7.36361541e+07,  3.95797020e+08, -1.36775636e+09,  3.14017772e+09,
       -4.83985516e+09,  4.94926104e+09, -3.22014863e+09,  1.20651386e+09,
       -1.98137398e+08])

We test it:

In [60]:
ill_conditioned @ x

array([1.0000001 , 0.99999994, 0.99999999, 0.99999991, 0.99999997,
       0.99999984, 1.00000003, 0.99999988, 0.99999996, 0.99999992,
       0.99999989, 1.00000006, 0.99999996])

Very close to $b$ (a vector of ones). Compare with the result we obain using the inverse:

In [61]:
x2 = ill_inverse@b
ill_conditioned@x2

array([-21.89711892, -21.65263147, -19.18224112, -17.1135844 ,
       -15.4517454 , -14.09137024, -12.95361918, -11.98483408,
       -11.14789288, -10.41627753,  -9.77044733,  -9.19561241,
        -8.68032324])

And compare with what we obtain using the modified inverse (with the small perturbation):

In [62]:
x3 = better_inv@b
ill_conditioned@x3

array([1.00160478, 0.99015151, 0.99379173, 1.00807935, 1.01921242,
       1.02373631, 1.02185175, 1.01473545, 1.00365078, 0.98968786,
       0.97371675, 0.95640769, 0.93826756])

Better... but solving the linear system is superior. 

**Remark:** Finding an inverse might be advantageous if several linear systems with the smae matrices have to be solved one after the other. 

<a id="exercises"></a>

## Exercises

2. Create a function  'special_gaussian(n)'  that generates a sample of $n$ independent Gaussians, where the variance of the $i$th component is $1/i$. (Note: You must use np.random.randn). Do not forget to avoid erros and test your function.

Idea: If $z\sim N(0,1)$ then $a*Z \sim N(0,a^2)$, hence if we want the variance to be 1/i, just multiply z by $\sqrt{1/i}$

In [0]:
np.random.randn?

In [63]:
def special_gaussian(n):
    
    if type(n)!= int:
        raise TypeError('n must be integer')

    if n<=0:
        raise ValueError('n must be positive')
    
    # We assume mean zero Gaussians. If X is a standard Gaussian, aX is a Gaussian with variance a^2
    variance = 1/np.arange(1,n+1)
    return np.random.randn(n)*(variance**0.5)
    
    

    
    

In [64]:
special_gaussian(10)

array([-0.01523126,  0.09031024,  0.47027014, -0.50985465, -0.12173321,
       -0.30831804, -0.75261619,  0.27876617,  0.14566716, -0.08077482])

2. We consider a one-period market model in a finite probability space. 

Create a function 'complete_market_1p(S0,S1)' that receives a vector S0 with the initial prices of the assets in a market, and a matrix S1 that gives the prices of each asset in the market under each scenario, and returns a boolean that states if the market is complete or not.

Idea: suppose the $S_1$ has shape $(m,n)$, $m$ for asset and $n$ for random state. if a market is compelete then the rank of S1 must be $rank(S_1)>= n$

In [65]:
def complete_market_1p(S0,S1):
    # We use here the convention that every row is an asset. As in the lecture notes, 
    # we just need to verify that the range of the transpose is full.
    return np.linalg.matrix_rank(S1.T)==S1.shape[1]  #Check the help of numpy for more on the function matrix_rank


# An example of an incomplete market (Example 1.35 LN)
S0 = np.array([1,2])
S1 = np.array([[1,2,1],[3,2,1]])
complete_market_1p(S0,S1)


False

In [66]:
# A complete example

S0 = np.array([1,1.5,2])
S1 = np.array([[1,1,1],[0.5,1,2],[3,1.5,1.5]])

complete_market_1p(S0,S1)


True

4.  Create a function 'is_SDF(S0,S1,P,M)' that receives a vector S0 (in $R^n$) with the initial prices of the assets in a market, a matrix S1 (in $R^{n\times k}$) that gives the prices of each asset in the market under each scenario, a vector $P$ with the probability of each scenario, and a candidate to be an SDF $M$ . The function returns a boolean that states if the $M$ is and SDF for the market with the given data or not.

In [67]:
def is_SDF(S0,S1,P,M):
    # We use here the convention that every row is an asset. As in the lecture notes, 
    # we just need to verify whether the expectation of each price times the SDF candidate equals the initial price.
    
    epsilon = 1e-6
    aux = S1@(M*P)
    return np.linalg.norm(aux - S0)< epsilon #Check the help of numpy for more on the function matrix_rank



In [68]:
S0 = np.array([1,1.5,2])
S1 = np.array([[1,1,1],[0.5,1,2],[3,1.5,1.5]])
P = np.array([1./4,1./2,1./4])
M = np.array([4/3,0,8/3])
assert is_SDF(S0,S1,P,M)
assert not is_SDF(S0,S1,P,np.ones(3))





